# Created on: Oct 29, 2012
#     Author: jorge
# Configuration for subscribers to cmd_vel sources. This file is provided just as an example.
# Typically automatic controllers, as ROS navigation stack should have the minimum priority
#
# Used with example.launch
#
# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides cmd_vel messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT
#   short_desc:     Short description (optional)

cmd_vel_mux:
  ros__parameters:
    subscribers:
      name: ["Default input", "Navigation stack", "Navigation stack controller", "Remote control", "Web Application", "Keyboard operation"]
      topic: ["input/default", "input/navigation", "input/joystick", "input/remote", "input/webapp", "input/keyop"]
      timeout: [0.1, 0.5, 0.1, 0.1, 0.3, 0.1]
      priority: [0, 1, 10, 9, 8, 7]
      short_desc: ["The default cmd_vel, controllers unaware we are multiplexing cmd_vel", "Navigation stack", "Navigation stack remote control", "Remote control", "Web application", "Keyboard operation"]
